version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

    allow:
      - dependency-type: "direct"

    open-pull-requests-limit: 5
